#!/bin/sh
#
# @name Mini-E
#
# @type Standard VTOL
# @class VTOL
#
# @maintainer Sean Bazzocchi <sean.bazzocchi@gmail.com>
#
# @output MAIN1 motor 1
# @output MAIN2 motor 2
# @output MAIN3 motor 3
# @output MAIN4 motor 4
# @output AUX1 Aileron 1
# @output AUX2 Aileron 2
# @output AUX3 Elevator
# @output AUX4 Rudder
# @output AUX5 Throttle
#


sh /etc/init.d/rc.vtol_defaults

if [ $AUTOCNF = yes ]
then
	#Temp for tuning indoor
	param set MC_ARIMODE 2 			#Set to 0 when tuning innerloop, 2 when tuned
	param set MC_ACRO_EXPO 0
	param set MC_ACRO_EXPO_Y 0
	param set MC_ACRO_SUPEXPO 0
	param set MC_ACRO_SUPEXPO_Y 0
	param set MC_ACRO_P_MAX 65
	param set MC_ACRO_R_MAX 65
	param set MC_ACRO_Y_MAX 30

##SYSTEMS
	#Actuator settings
	param set PWM_AUX_DIS5 950
	param set VT_IDLE_PWM_MC 1170

	#Power
	param set UAVCAN_ENABLE 0
	param set BAT_A_PER_V 0.2
	param set BAT1_A_PER_V 0.2
	param set BAT1_V_DIV 14.3
	param set BAT_V_DIV 14.3
	param set BAT_N_CELLS 6
	param set BAT1_N_CELLS 6
	param set BAT_CAPACITY 8100
	param set BAT1_CAPACITY 8100
	param set BAT_R_INTERNAL 0.01
	param set BAT1_R_INTERNAL 0.01

	#LIDAR settings
	param set SENS_EN_LL40LS 2
	param set EKF2_RNG_AID 1
	param set EKF2_RNG_A_HMAX 10
	param set EKF2_RNG_A_VMAX 2
	param set EKF2_RNG_PITCH 0

	#Pressure sensors
	param set CAL_AIR_TUBELEN 0.04

	#GPS
	param set GPS_1_CONFIG 104 #Set Primary GPS to input UART4
	param set GPS_2_CONFIG 201 #Set Secondary GPS to input GPS
	param set SER_TEL4_BAUD	0 #Auto baud for GPS
	param set EKF2_GPS_MASK 7 #Type of meshing for the 2 GPS
	param set EKF2_GPS_V_NOISE 0.2 #Reduce gps noise thanks to RTK (set to default if no RTK)
	param set EKF2_GPS_P_NOISE 0.2 #Reduce gps noise thanks to RTK (set to default if no RTK)
	param set EKF2_HGT_MODE 0 #Set to default (0 baro) if no RTK gps or 1 (GPS) if RTK

	#Telemetry
	param set SER_TEL1_BAUD 115200
	param set MAV_PROTO_VER 2 #Force mavlink 2.0 to be the protocol (needed for RTK)

	#Sensor rotation
	param set SENS_BOARD_ROT 8

	#Motor settings
	param set THR_MDL_FAC 0.55
	param set PWM_MIN 1100

	#Logging settings
	param set SDLOG_PROFILE 27
	param set SDLOG_UTC_OFFSET -480

	#Arming
	param set CBRK_VTOLARMING 159753
	param set COM_ARM_MAG_ANG -1

	#Filters
	param set IMU_DGYRO_CUTOFF 30
	param set IMU_GYRO_NF_BW 4
	param set IMU_GYRO_NF_FREQ 12

	#Mission and safety
	param set COM_RC_LOSS_T 1 #Seconds of lost radio to trigger failsafe


##MULTI-COPTER
	#Rate controller
	param set MC_ROLLRATE_P 0.3
	param set MC_ROLLRATE_I 0.2
	param set MC_ROLLRATE_D 0.001

	param set MC_PITCHRATE_P 0.23
	param set MC_PITCHRATE_I 0.25
	param set MC_PITCHRATE_D 0.003

	param set MC_YAWRATE_P 0.6
	param set MC_YAWRATE_I 0.02
	param set MC_YAWRATE_D 0

	#Attitude controller
	param set MC_ROLL_P 4
	param set MC_PITCH_P 4
	param set MC_YAW_P 0.6

	#Max rates
	param set MC_YAWRATE_MAX 30
	param set MPC_YAWRAUTO_MAX 30

	#Position Controller
	param set MPC_XY_P 0.3

	param set MPC_JERK_AUTO 4
	param set MPC_JERK_MAX 5
	param set MPC_JERK_MIN 5
	param set MPC_ACC_HOR 2
	param set MPC_ACC_HOR_MAX 2

	#Takeoff
	param set MPC_TKO_SPEED 1

	#Landing

	#Motor settings
	param set MPC_THR_HOVER 0.7
	param set MPC_THR_MIN 0.1


##FIXED-WING
	#Airspeed
	param set FW_AIRSPD_MAX 35
	param set FW_AIRSPD_MIN 13
	param set FW_AIRSPD_TRIM 17.5

	#FW Tuning
	param set FW_PR_FF 0.5
	param set FW_PR_I 0.02
	param set FW_PR_IMAX 0.4
	param set FW_PR_P 0.08
	param set FW_RR_FF 0.6
	param set FW_RR_I 0.01
	param set FW_RR_IMAX 0.2
	param set FW_RR_P 0.05
	param set FW_THR_CRUISE 0.75

##VTOL transition tuning
	param set VT_ARSP_BLEND 8
	param set VT_ARSP_TRANS 15
	param set VT_F_TRANS_THR 1
	param set VT_MOT_ID 1234
	param set VT_FW_MOT_OFFID 1234
	param set VT_TYPE 2

##TANSMITTER
	param set COM_FLTMODE1 6 #Acro
	param set COM_FLTMODE2 0 #Manual
	param set COM_FLTMODE3 2 #Position
	param set COM_FLTMODE4 3 #Mission
	param set COM_FLTMODE5 5 #Return
	param set COM_FLTMODE6 4 #Hold

	param set RC_RSSI_PWM_CHAN 12
	param set RC_RSSI_PWM_MAX 2000
	param set RC_RSSI_PWM_MIN 1000

fi

set MAV_TYPE 22

set MIXER mini_e
set MIXER_AUX mini_e

set PWM_OUT 1234
