#!/bin/sh
#
# @name Tarot IronMan 650
#
# @type Quadrotor x
# @class Copter
#
# @maintainer Sean Bazzocchi <sean.bazzocchi@gmail.com>
#
# @board px4_fmu-v2 exclude
# @board intel_aerofc-v1 exclude
# @board bitcraze_crazyflie exclude
#

sh /etc/init.d/rc.mc_defaults

set MIXER quad_tarot_650
set PWM_OUT 1234

if [ $AUTOCNF = yes ]
then

	#Temp for tuning
	param set MC_AIRMODE 0
	param set MC_ACRO_EXPO 0
	param set MC_ACRO_EXPO_Y 0
	param set MC_ACRO_SUPEXPO 0
	param set MC_ACRO_SUPEXPOY 0
	param set MC_ACRO_P_MAX 100
	param set MC_ACRO_R_MAX 100
	param set MC_ACRO_Y_MAX 50


	#Power
	param set BAT_N_CELLS 6
	param set BAT1_N_CELLS 6
	param set BAT_CAPACITY 6300
	param set BAT1_CAPACITY 6300
	param set BAT_R_INTERNAL 0.01
	param set BAT1_R_INTERNAL 0.01

	#General sensor settings

	#Telemetry settings
	param set SER_TEL1_BAUD 115200

	#LIDAR settings
	param set SENS_EN_LL40LS 2
	param set EKF2_RNG_AID 1
	param set EKF2_RNG_A_HMAX 10
	param set EKF2_RNG_A_VMAX 2
	param set EKF2_RNG_NOISE 0.05
	param set EKF2_RNG_PITCH 0
	param set EKF2_RNG_POS_X 0.05
	param set EKF2_RNG_POS_Y 0.045
	param set EKF2_RNG_POS_Z 0.03


	#Rate controller
	param set MC_ROLLRATE_P 0.1
	param set MC_ROLLRATE_I 0.1
	param set MC_ROLLRATE_D 0.002

	param set MC_PITCHRATE_P 0.1
	param set MC_PITCHRATE_I 0.1
	param set MC_PITCHRATE_D 0.002

	param set MC_YAWRATE_P 0.4
	param set MC_YAWRATE_I 0.35
	param set MC_YAWRATE_D 0

	#Attitude controller
	param set MC_ROLL_P 3.5
	param set MC_PITCH_P 3.5
	param set MC_YAW_P 3.2

	#Motor settings
	param set PWM_MIN 1100
	param set THR_MDL_FAC 0.031
	param set MPC_THR_HOVER 0.35

	#Logging settings
	param set SDLOG_PROFILE 27
	param set SDLOG_UTC_OFFSET -480

fi
