#!/bin/sh
#
# @name MIMIQLight
#
# @type Quadrotor x
# @class Copter
#
# @maintainer Sean Bazzocchi <sean.bazzocchi@gmail.com>
#

. ${R}etc/init.d/rc.mc_defaults

#Temp for tuning
	param set-default MC_AIRMODE 2 #Set to 0 when tuning innerloop, 2 when tuned

##SYSTEMS
	#Power
	param set-default BAT1_N_CELLS 14
	param set-default BAT1_CAPACITY 6000 #23Ah
	param set-default BAT1_R_INTERNAL 0.01

	#LIDAR settings
	param set-default SENS_EN_LL40LS 2
	param set-default EKF2_RNG_A_HMAX 10
	param set-default EKF2_RNG_A_VMAX 2
	param set-default EKF2_RNG_POS_X -0.22784 
	param set-default EKF2_RNG_POS_Y -0.07605 
	param set-default EKF2_RNG_POS_Z 0.02721 
	param set-default EKF2_MIN_RNG 0.4 

	#GPS
	param set-default EKF2_GPS_POS_X -0.29679  
	param set-default EKF2_GPS_POS_Y 0.27433  
	param set-default EKF2_GPS_POS_Z -0.13001  

	#IMU position
	param set-default EKF2_IMU_POS_X -0.08693  
	param set-default EKF2_IMU_POS_Y -0.00195  
	param set-default EKF2_IMU_POS_Z  -0.00126 

	#Serial comms settings
	param set-default SER_TEL1_BAUD 115200
	param set-default MAV_PROTO_VER 2 #Force mavlink 2.0 to be the protocol (needed for RTK)

	#Sensor rotation
	param set-default SENS_BOARD_ROT 4 #Yaw 180

	#Motor settings
	param set-default THR_MDL_FAC 0.4893
	param set-default UAVCAN_ENABLE 3
	param set-default UAVCAN_EC_FUNC1 101
	param set-default UAVCAN_EC_FUNC2 102
	param set-default UAVCAN_EC_FUNC3 103
	param set-default UAVCAN_EC_FUNC4 104

	#TANSMITTER
	param set-default COM_FLTMODE1 6 #Acro
	param set-default COM_FLTMODE2 8 #Stabilized
	param set-default COM_FLTMODE3 2 #Position
	param set-default COM_FLTMODE4 3 #Mission
	param set-default COM_FLTMODE5 5 #Return
	param set-default COM_FLTMODE6 4 #Hold

	param set-default RC_RSSI_PWM_CHAN 12
	param set-default RC_RSSI_PWM_MAX 2000
	param set-default RC_RSSI_PWM_MIN 1000

	param set-default COM_KILL_DISARM 2

	#Safety
	param set-default COM_RC_LOSS_T 1 #Seconds of lost radio to trigger failsafe
	param set-default COM_DL_LOSS_T 30 #Seconds of lost GS link to trigger failsafe
	param set-default NAV_DLL_ACT 2 #Return after COM_DL_LOSS_T of lost comms
	param set-default COM_RC_STICK_OV 30 #Stick treshold to revert to position mode
	param set-default GF_ACTION 1
	#Mission
	param set-default RTL_RETURN_ALT 50 

	#Logging settings
	param set-default SDLOG_PROFILE 27
	param set-default SDLOG_UTC_OFFSET -480

	#Arming
	param set-default MAN_ARM_GESTURE 0

	#Filters
	param set-default IMU_GYRO_CUTOFF 30
	param set-default IMU_DGYRO_CUTOFF 20
	param set-default IMU_ACCEL_CUTOFF 20
	param set-default IMU_GYRO_DNF_EN 2
	param set-default IMU_GYRO_FFT_EN 1
	param set-default IMU_GYRO_FFT_MIN 10


##CONTROLLER TUNING
	#Rate controller
	param set-default MC_ROLLRATE_P 0.146
	param set-default MC_ROLLRATE_I 0.199
	param set-default MC_ROLLRATE_D 0.0039

	param set-default MC_PITCHRATE_P 0.1499
	param set-default MC_PITCHRATE_I 0.205
	param set-default MC_PITCHRATE_D 0.004

	param set-default MC_YAWRATE_P 0.189
	param set-default MC_YAWRATE_I 0.1836
	param set-default MC_YAWRATE_D 0.0063

	#Attitude controller
	param set-default MC_ROLL_P 6
	param set-default MC_PITCH_P 6
	param set-default MC_YAW_P 2.8

	#Max rates
	param set-default MC_ROLLRATE_MAX 120
	param set-default MC_PITCHRATE_MAX 120
	param set-default MC_YAWRATE_MAX 150

	#Max rates ACRO
	param set-default MC_ACRO_P_MAX 110
	param set-default MC_ACRO_R_MAX 110
	param set-default MC_ACRO_Y_MAX 80

	#Motor settings
	param set-default MPC_THR_HOVER 0.5

	#Autotune
	param set-default MC_AT_EN 1

##Mixer
	param set-default CA_ROTOR_COUNT 4

	#Rotor0 front-right
	param set-default CA_ROTOR0_PX 0.626
	param set-default CA_ROTOR0_PY 0.589
	param set-default CA_ROTOR0_PZ 0.08116
	param set-default CA_ROTOR0_AX -0.061628
	param set-default CA_ROTOR0_AY 0.061628
	param set-default CA_ROTOR0_AZ -0.9961947
	param set-default CA_ROTOR0_CT 136.1
	param set-default CA_ROTOR0_KM 0.0358

	#Rotor1 rear-left
	param set-default CA_ROTOR1_PX -0.626
	param set-default CA_ROTOR1_PY -0.589
	param set-default CA_ROTOR1_PZ 0.08116
	param set-default CA_ROTOR1_AX 0.061628
	param set-default CA_ROTOR1_AY -0.061628
	param set-default CA_ROTOR1_AZ -0.9961947
	param set-default CA_ROTOR1_CT 136.1
	param set-default CA_ROTOR1_KM 0.0358

	#Rotor2 front-left
	param set-default CA_ROTOR2_PX 0.626
	param set-default CA_ROTOR2_PY -0.589
	param set-default CA_ROTOR2_PZ 0.08116
	param set-default CA_ROTOR2_AX -0.061628
	param set-default CA_ROTOR2_AY -0.061628
	param set-default CA_ROTOR2_AZ -0.9961947
	param set-default CA_ROTOR2_CT 136.1
	param set-default CA_ROTOR2_KM -0.0358

	#Rotor3 rear-right
	param set-default CA_ROTOR3_PX -0.626
	param set-default CA_ROTOR3_PY 0.589
	param set-default CA_ROTOR3_PZ 0.08116
	param set-default CA_ROTOR3_AX 0.061628
	param set-default CA_ROTOR3_AY 0.061628
	param set-default CA_ROTOR3_AZ -0.9961947
	param set-default CA_ROTOR3_CT 136.1
	param set-default CA_ROTOR3_KM -0.0358