#!/bin/sh
#
# @name Standard VTOL
#
# @type Standard VTOL
#

sh /etc/init.d/rc.vtol_defaults

if [ $AUTOCNF = yes ]
then

	#Temp for tuning
	param set MC_AIRMODE 0
	param set MC_ACRO_EXPO 0
	param set MC_ACRO_EXPO_Y 0
	param set MC_ACRO_SUPEXPO 0
	param set MC_ACRO_SUPEXPOY 0
	param set MC_ACRO_P_MAX 100
	param set MC_ACRO_R_MAX 100
	param set MC_ACRO_Y_MAX 50

##SYSTEM


##Multi-copter
	#Rate controller
	param set MC_ROLLRATE_P 0.38
	param set MC_ROLLRATE_I 0.2
	param set MC_ROLLRATE_D 0.001

	param set MC_PITCHRATE_P 0.23
	param set MC_PITCHRATE_I 0.25
	param set MC_PITCHRATE_D 0.003

	param set MC_YAWRATE_P 0.6
	param set MC_YAWRATE_I 0.02
	param set MC_YAWRATE_D 0

	#Attitude controller
	param set MC_ROLL_P 5
	param set MC_PITCH_P 6.5
	param set MC_YAW_P 0.6

	#Max rates
	param set MC_YAWRATE_MAX 30
	param set MPC_YAWRAUTO_MAX 30

	#Position Controller
	param set MPC_XY_P 0.3

	param set MPC_JERK_AUTO 4
	param set MPC_JERK_MAX 5
	param set MPC_JERK_MIN 5
	param set MPC_ACC_HOR_MAX 2

	#Takeoff
	param set MPC_TKO_SPEED 1

	#Landing

	#Motor settings
	param set MPC_THR_HOVER 0.66
	param set MPC_THR_MIN 0.1


#Fixed-wing
	param set FW_AIRSPD_MAX 35
	param set FW_AIRSPD_MIN 13
	param set FW_AIRSPD_TRIM 17.5


	param set NAV_ACC_RAD 5
	param set NAV_LOITER_RAD 80


#VTOL transition
	param set VT_F_TRANS_DUR 15
	param set VT_F_TRANS_THR 1
	param set VT_ARSP_TRANS 17.5
	param set VT_MOT_ID 1234
	param set VT_FW_MOT_OFFID 1234
	param set VT_TYPE 2
	param set VT_B_TRANS_DUR 8


##General settings
	#Logging settings
	param set SDLOG_PROFILE 27
	param set SDLOG_UTC_OFFSET -480

	#Mission
	param set MIS_LTRMIN_ALT 10
	param set MIS_TAKEOFF_ALT 10
	param set MIS_YAW_TMT 10
fi

set MAV_TYPE 22

set MIXER_FILE etc/mixers-sitl/mini_e.main.mix
set MIXER custom
