#!/bin/sh
#
# @name Mini-e Quadrotor SITL
#
# @type Quadrotor Wide
#
# @maintainer Sean Bazzocchi <sean.bazzocchi@gmail.com>
#

sh /etc/init.d/rc.mc_defaults

if [ $AUTOCNF = yes ]
then
	#Temp for tuning
	param set MC_AIRMODE 0
	param set MC_ACRO_EXPO 0
	param set MC_ACRO_EXPO_Y 0
	param set MC_ACRO_SUPEXPO 0
	param set MC_ACRO_SUPEXPOY 0
	param set MC_ACRO_P_MAX 100
	param set MC_ACRO_R_MAX 100
	param set MC_ACRO_Y_MAX 50

	#Rate controller
	param set MC_ROLLRATE_P 0.38
	param set MC_ROLLRATE_I 0.2
	param set MC_ROLLRATE_D 0.001

	param set MC_PITCHRATE_P 0.23
	param set MC_PITCHRATE_I 0.25
	param set MC_PITCHRATE_D 0.003

	param set MC_YAWRATE_P 0.6
	param set MC_YAWRATE_I 0.02
	param set MC_YAWRATE_D 0

	#Attitude controller
	param set MC_ROLL_P 5
	param set MC_PITCH_P 6.5
	param set MC_YAW_P 0.6

	#Max rates
	param set MC_YAWRATE_MAX 30
	param set MPC_YAWRAUTO_MAX 30

	#Position Controller
	param set MPC_XY_P 0.3
	param set MPC_JERK_AUTO 4
	param set MPC_JERK_MAX 5
	param set MPC_JERK_MIN 5

	#Motor settings
	param set PWM_MIN 1100
	param set THR_MDL_FAC 0 #Real:0.055
	param set MPC_THR_HOVER 0.66

	#Logging settings
	param set SDLOG_PROFILE 27
	param set SDLOG_UTC_OFFSET -480

fi

set MIXER mini_e

